<div class="filecont">
	<div class="name">{name}</div>
	<div class="author"><a href="?author={authorId}">{author}</a></div>
	<a href="?file={id}">
		<div class="popup">
			<div class="description">{description}</div>
			<div class="downloads">{downloads}</div>
			<div class="rating">+{upvotes}/-{downvotes}</div>
		</div>
		<img src="{image}" alt="{name}" class="{class}">
	</a>
	<input class="fileDlCheckbox" type="checkbox" data-id="{id}">
</div>
